services:
  website:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file: .env
    volumes:
      - ..:/website:cached
      - node_modules:/website/node_modules
    command: "sleep infinity"

volumes:
  node_modules:
